# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 10:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='\u5185\u5bb9')),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u65f6\u95f4')),
            ],
            options={
                'db_table': 'comment',
                'verbose_name': '\u8bc4\u8bba',
                'verbose_name_plural': '\u8bc4\u8bba',
            },
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True, verbose_name='\u5546\u54c1\u540d\u79f0')),
            ],
            options={
                'db_table': 'commodity',
                'verbose_name': '\u5546\u54c1',
                'verbose_name_plural': '\u5546\u54c1',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='id_Commodity',
            field=models.ForeignKey(blank=True, db_column='id_Commodity', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MyApp.Commodity', verbose_name='\u5546\u54c1'),
        ),
    ]
