# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 04:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordsStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u5173\u952e\u5b57')),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='\u6570\u91cf')),
                ('id_Commodity', models.ForeignKey(blank=True, db_column='id_Commodity', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MyApp.Commodity', verbose_name='\u5546\u54c1')),
            ],
            options={
                'db_table': 'keywords',
                'verbose_name': '\u5173\u952e\u5b57',
                'verbose_name_plural': '\u5173\u952e\u5b57',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='sentiment',
            field=models.FloatField(blank=True, null=True, verbose_name='\u60c5\u611f\u503c'),
        ),
    ]
