# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_auto_20160714_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordsstatistics',
            name='amount',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='\u6570\u91cf'),
        ),
    ]
